# This is a basic workflow to help you get started with Actions

name: Code Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test_success:
    name: Passing Submission
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout Code
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
